### ISSUE TITLE
Error in if (revision < 57) { : argument is of length zero 

### ISSUE THREAD

**Issue by waterhanBsu** [chrisschuerz/SWATplusR#26] opened 2021-01-03 01:13 UTC
Dear Chris,

I hope you are having a great start of the new year. 

I'm using your SWATplusR packages (0.3.3.9004) in R (R version 4.0.2). I had a hard time using optim to find the best parameter set, as none of the parameters seems to be very sensitive to model performance and always receive the same best NSE value. So I was trying to use SCEoptim function as it can give out more details, but I keep on receiving the error message _Error in if (revision < 57) { : argument is of length zero_ 

I tried to assign rev <- 59.3 or revision <- 59.3 outside of the SCEoptim function, but neither solves the issues. I did a bit search and thought you probably have had some updates to remove this if argument? I'd appreciate if you could provide some insights on how to solve this problem.

Thanks so much.

Best regards

Jim

**Comment by chrisschuerz** [comment] 2021-01-04 08:59
Hi Jim,

yes there is now a workaround implemented in `SWATplusR` that solves this issue (as you already use the most recent version you should be fine.

The issue is caused by a small routine that tries to find out which revision of SWAT+ you are using. This is done by running your executable in an empty folder, simply to read out the header of the running exe. I n rare cases this routine can fail. But with the optimization you start the model many times. This makes this rare case just much more likely to occur. 

To skip the routine that finds the revision number you as a user can also define the revision number of your executable manually by defining the input argument `revision`. E.g. if you use the the SWAT+ revision 59.3 simply add `run_swatplus(..., revision = 59.3)`.

I hope this helps.
Best
Christoph

**Comment by waterhanBsu** [comment] 2021-01-06 03:50
Thank you, Chris. It worked after adding the revision number within the run_swatplus function. My old question was still there though:
For some reason, my SWATplusR runs are not sensitive to any parameter change except ET. The simulated discharge is very low. I compared the discharge with the output directly run with SWATplusEditor and they are very different. Have you noticed anything that the code does not read in correctly?  

FYI, I snipped a picture here for two runs with exactly the same files from the TxtInOut folder, using SwatPlusEditor and SwatPlusR. 

![Capture](https://user-images.githubusercontent.com/70441314/103726814-cfd66880-4fa7-11eb-8c88-93ee69f33070.JPG)

**Comment by chrisschuerz** [comment] 2021-01-07 08:54
Hi Jim,

I wanted to come back to the issue that you documented in an edited version of your reply. The behavior you plotted with the comparison between the SWATeditor and running your model from R is odd. THat should in fact not be the case if both use the same executable file. Did you solve this problem or does it still exist?

**Comment by waterhanBsu** [comment] 2021-01-07 13:40
Chris, that was my mistake of actually changing the curve number values in calibration.cal file, so I deleted the post. But I have not figured out why my model has no sensitivity with parameters in SWATplusR, Manual calibration in SWATplus Editor did change the model performance. I suspect there is a disconnection somewhere but could not figure out. Thanks for looking into this issue.

**Comment by waterhanBsu** [comment] 2021-01-12 15:22
Chris, thanks for the help. Yes, the fix of file.cio solved the issue. So after I do calibration and optimization, and get the best set of parameters, do I manually update them in different files in the TxtInOut? I don't find SWATplusR has an option to update them. This may not be directly related to this thread. Let me know if I should open a new thread.

**Comment by chrisschuerz** [comment] 2021-05-05 06:32
@waterhanBsu sorry for this really late reply. A workaround to get a model with your best parameter set is to rerun the model with the best parameter combination. You can set the option `keep_folder = TRUE` to not delete the '.model_run' folder structure in your 'TxtInOut'. After running the model the model in 'TxtInOut/.model_run/thread_1' has the right parametrization. 
I planned however to add a function for only writing the parameters to generate a folder for you best model. Unfortunately I did not have the time for that yet.

**Comment by chrisschuerz** [comment] 2021-05-05 06:33
If it is OK for you I would close this issue. If there are still things to discuss, please reopen this one or post a new issue

**Closed by chrisschuerz** 2021-05-05 06:33 UTC

**Comment by waterhanBsu** [comment] 2021-05-05 12:13
Of course, Chris. Please close it. Thank you for your help during the modeling process.

------------------

Bangshuai Han, Ph.D.
Assistant Professor of Water Resources
Chair of Future Risk Committee of the American Water Resources Association

Environment, Geology and Natural Resources
Ball State University

765-285-5790

https://bangshuaihangroup.weebly{dot}com/<https://bangshuaihangroup.weeblycom/>
www.bsu.edu/egnr


P Please consider the environment before printing this email.

________________________________
