### ISSUE TITLE
Error trying to modify parameters in *.sdr files

### ISSUE THREAD

**Issue by jsacerot** [chrisschuerz/SWATplusR#30] opened 2021-04-15 01:34 UTC
I am trying to modify some of the tile drain parameters in files *.sdr, but SWATplusR returns the following error:

**Error in { : 
  task 1 failed - "no applicable method for 'filter' applied to an object of class "NULL""**

Could you please provide me some guidance on how to fix this problem? The parameters that I want to modify are the following:

par_names <- c(**'LATKSATF.sdr|change = absval|luse %in% c("CORN", "SOYB", "WWHT")'**, 
                   'SSTMAXD_BSN.bsn|change = absval', 
                   'DEP_IMP.hru|change = absval|luse %in% c("CORN", "SOYB", "WWHT")',
                   **'DRAIN_CO.sdr|change = absval|luse %in% c("CORN", "SOYB", "WWHT")'**)
                   
Thank you!

**Comment by jsacerot** [comment] 2021-04-15 02:27
I found an error in my code when defining the parameters using single and double quotation marks. This is the correct form to set the parameters:

par_names <- c("LATKSATF.sdr|change = absval|luse %in% c('CORN', 'SOYB', 'WWHT')", 
                   "SSTMAXD_BSN.bsn|change = absval", 
                   "DEP_IMP.hru|change = absval|luse %in% c('CORN', 'SOYB', 'WWHT')",
                   "DRAIN_CO.sdr|change = absval|luse %in% c('CORN', 'SOYB', 'WWHT')")

**Once I successfully ran the simulations, however, I noticed in the thread folders that the parameters in the *.sdr files were not properly modified (See attached files). Any help will be appreciated.**

[sdr_example.zip](https://github.com/chrisschuerz/SWATplusR/files/6314795/sdr_example.zip)

**Comment by chrisschuerz** [comment] 2021-04-15 09:15
I see. I will look into that. The parameter format when writing the parameter into the file is also off. I am not sure how SWAT will interpret that. I will check that as well.

I hope that I find an answer soon
Best Christoph

**Comment by WillemVervoort** [comment] 2021-04-15 09:18
Chris,
this looks like an error related to the use of the function filter in
multiple packages (dplyr, base). You probably just need to insert dplyr::
filter or base::filter or the relevant package to remove this error

Regards
Willem

**Comment by chrisschuerz** [comment] 2021-04-15 09:25
@WillemVervoort I think filter is not the issue here. In the function headers I specificly define the functions that are used from which packages they should be taken ( with e.g. `@ImportFrom dplyr filter select`). I will however check if this is done properly in this case. 
In any case I also recently found some issues with the subsetting of parameters that I wanted to look into.

**Comment by jsacerot** [comment] 2021-04-15 17:17
@chrisschuerz Most SWAT input files are read using free format reading. So, I do not think the displacement issue of the SDRAIN parameter (or any other) in files *.sdr will affect the model:

Line 82 of 'readsdr.f' :  read (112,*,iostat=eof) sdrain(ihru)

**Comment by chrisschuerz** [comment] 2021-04-15 19:26
@jsacerot Thanks for sharing the respective line of code. Then it should be good. Anyways, the parameter did not change and I will look into that.

**Comment by chrisschuerz** [comment] 2021-04-18 19:36
@jsacerot I fixed the issue with the .sdr files. The reason for the issue was that parameters in all table like input files do have 16 digits except the .sdr files. As I never used the .sdr files in the calibration so far I never checked that. In the development version of `SWATplusR` I modified the parameter handling now and made it more flexible for different lengths of parameter values. So it should also work with .sdr parameters now.

You can test the fix after installing `SWATplusR` 0.3.4.9004 from the dev branch with

```r
remotes::install_github('chrisschuerz/SWATplusR', ref = 'dev')
```

Please give me feedback if it works now in your case or not. This version does not work with SWAT+ yet as it requires a few modifications that I did not manage to do today, but which I will update in the following days.

**Comment by chrisschuerz** [comment] 2021-04-19 10:32
@jsacerot Sorry one minor addition. I had to fix two small things that were not working properly with that fix on all the computers I tested it on. I hope it works now. The most recent `dev` version is now 0.3.4.9006

**Comment by jsacerot** [comment] 2021-04-20 17:00
@chrisschuerz Thank you for the update. I am trying to install the dev branch of SWATpluR but it is failing due to the package tibble:

package ‘tibble’ successfully unpacked and MD5 sums checked
Error: Failed to install 'SWATplusR' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘tibble’
  
 Any suggestions? Thanks!

**Comment by jsacerot** [comment] 2021-04-20 17:30
@chrisschuerz Thank you for the update. I installed the dev branch but the command run_swat2012 failed:

Error in str_length(tmp[par_pos]) : could not find function "str_length"

Could you please guide me on how to fix this new issue? Thank you!

**Comment by chrisschuerz** [comment] 2021-04-20 18:27
Hi thanks for the info. I found the issue. I just forgot to add a function import in the last version. This is now fixed in version 0.3.4.9007. 
If such an issue arises in the future and you need a very quick fix you can just load the R package that contains the function (you can find that out with e.g. `??str_length`). Well this works if the package is installed on your machine. Otherwise just search for it in the internet :)

**Comment by jsacerot** [comment] 2021-04-20 19:00
@chrisschuerz Thank you for the prompt response. To be honest, I thought that str_lenght was one of the functions of your library. I installed the latest dev version but it seems the changes are triggering more errors:

Error: `nm` must be `NULL` or a character vector the same length as `x`
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
`nm` must be `NULL` or a character vector the same length as `x`
Backtrace:
  1. SWATplusR::run_swat2012(...)
 11. purrr::map_df(., ~set_names(.x, par_name))
 12. purrr::map(.x, .f, ...)
 13. SWATplusR:::.f(.x[[i]], ...)
 14. rlang::set_names(.x, par_name)

**Comment by chrisschuerz** [comment] 2021-04-21 07:03
sorry my mistake. I forgot to push that fix to the online repo although I had soplved this already locally. This should now be fixed in version 0.3.4.9008.

**Comment by jsacerot** [comment] 2021-04-21 20:33
@chrisschuerz For some reason your URL cannot be accessed:

> remotes::install_github('chrisschuerz/SWATplusR', ref = 'dev')
Downloading GitHub repo chrisschuerz/SWATplusR@dev
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/chrisschuerz/SWATplusR/tarball/dev'

**Comment by chrisschuerz** [comment] 2021-04-22 07:28
Hi I am really sorry for giving you such an unnecessarily hard time :) I tested the compatibility with SWAT+ yesterday night. As it seems to work correctly now with both models I merged everything into the main branch now. So you can install the official version 0.3.4 now from the main branch with `remotes::install_github('chrissschuerz/SWATplusR')`. I hope everything works now as intended. Otherwise you unfortunately know the procedure already well :)

**Closed** 2021-04-22 18:35 UTC

**Comment by chrisschuerz** [comment] 2021-04-23 06:21
Thanks for the great feedback. Good that it works properly now. It was already planned for a while to keep the strings in the input files while not slowing down the file writing. But the issue you posted was a good motivation to solve that as well. :) I also think it helps.
